name: tags_in_task
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: ralphpina <ralph.pina@gmail.com>

environment:
  sdk: '>=2.0.0-dev.1.2 <2.0.0'

dependencies:
  tags:
    path: ../tags

dev_dependencies:
  test: ^0.12.0
